apiVersion: 1

deleteDatasources:
  - name: Astra
    orgId: 1

datasources:
  - name: Astra Trace
    type: zipkin
    access: proxy
    url: "host.docker.internal:8081"
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    version: 1
  - name: Astra Query
    type: elasticsearch
    access: proxy
    url: "host.docker.internal:8081"
    password:
    user:
    database: testindex
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    jsonData:
      timeField: "@timestamp"
      esVersion: 7.0.0
      maxConcurrentShardRequests: 5
      logMessageField: "_source"
      logLevelField: ""
    version: 1
  - name: Astra Index
    type: elasticsearch
    access: proxy
    url: "host.docker.internal:8080"
    password:
    user:
    database: testindex
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: false
    jsonData:
      timeField: "@timestamp"
      esVersion: 7.0.0
      maxConcurrentShardRequests: 5
      logMessageField: "_source"
      logLevelField: ""
    version: 1
